In [209]:
import os
os.environ['KAGGLE_USERNAME']='mohamedfaheem123'
os.environ['KAGGLE_KEY']='KGAT_def3f224d8ab37aeeeef3311190d61b4'

In [210]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [211]:
!kaggle datasets download -d 'paramvir705/netflix-dataset'

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/paramvir705/netflix-dataset
License(s): apache-2.0
netflix-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [212]:
!unzip netflix-dataset.zip -d/content

Archive:  netflix-dataset.zip
replace /content/netflix_titles.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: yes
  inflating: /content/netflix_titles.csv

In [213]:
import pandas as pd
df=pd.read_csv('/content/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [214]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [215]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [216]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [217]:
df.shape

(8807, 12)

In [218]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [219]:
df = df.drop(columns=[
    'show_id',
    'cast'
])

df['duration'] = df['duration'].str.extract(r'(\d+)').fillna(0).astype(int)

In [220]:
df.columns

Index(['type', 'title', 'director', 'country', 'date_added', 'release_year',
       'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [221]:
df['date_added'] = pd.to_datetime(df['date_added'].str.strip())
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month
df.drop(columns='date_added', inplace=True)

In [222]:
import pandas as pd
if pd.api.types.is_string_dtype(df['duration']):
    df['duration'] = df['duration'].str.extract(r'(\d+)').fillna(0).astype(int)

In [223]:
df.head()

,type,title,director,country,release_year,rating,duration,listed_in,description,year_added,month_added
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2020,PG-13,90,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0
1,TV Show,Blood & Water,NaN,South Africa,2021,TV-MA,2,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0
2,TV Show,Ganglands,Julien Leclercq,NaN,2021,TV-MA,1,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0
3,TV Show,Jailbirds New Orleans,NaN,NaN,2021,TV-MA,1,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0
4,TV Show,Kota Factory,NaN,India,2021,TV-MA,2,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0

In [224]:
df["content_age"] = 2026 - df["release_year"]

In [225]:
df["duration_minutes"] = df["duration"]

In [226]:
df.isnull().sum()

type                   0
title                  0
director            2634
country              831
release_year           0
rating                 4
duration               0
listed_in              0
description            0
year_added            10
month_added           10
content_age            0
duration_minutes       0
dtype: int64

In [227]:
df.head()

,type,title,director,country,release_year,rating,duration,listed_in,description,year_added,month_added,content_age,duration_minutes
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2020,PG-13,90,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0,6,90
1,TV Show,Blood & Water,NaN,South Africa,2021,TV-MA,2,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0,5,2
2,TV Show,Ganglands,Julien Leclercq,NaN,2021,TV-MA,1,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0,5,1
3,TV Show,Jailbirds New Orleans,NaN,NaN,2021,TV-MA,1,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0,5,1
4,TV Show,Kota Factory,NaN,India,2021,TV-MA,2,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0,5,2

In [228]:
col_1=['director','country','rating']
for col in col_1:
  df[col].fillna(df[col].mode()[0], inplace=True)
df.isnull().sum()

/tmp/ipykernel_1080/1409695004.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

type                 0
title                0
director             0
country              0
release_year         0
rating               0
duration             0
listed_in            0
description          0
year_added          10
month_added         10
content_age          0
duration_minutes     0
dtype: int64

In [229]:
df["year_added"].fillna(df["year_added"].median(), inplace=True)
df["month_added"].fillna(df["month_added"].mode()[0], inplace=True)

/tmp/ipykernel_1080/384856772.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["year_added"].fillna(df["year_added"].median(), inplace=True)
/tmp/ipykernel_1080/384856772.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["month_added"].fillna(df["month_added"].mode()[0], inplace=True)

In [230]:
df.isnull().sum()

type                0
title               0
director            0
country             0
release_year        0
rating              0
duration            0
listed_in           0
description         0
year_added          0
month_added         0
content_age         0
duration_minutes    0
dtype: int64

In [231]:
df.head(5)

,type,title,director,country,release_year,rating,duration,listed_in,description,year_added,month_added,content_age,duration_minutes
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2020,PG-13,90,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0,6,90
1,TV Show,Blood & Water,Rajiv Chilaka,South Africa,2021,TV-MA,2,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0,5,2
2,TV Show,Ganglands,Julien Leclercq,United States,2021,TV-MA,1,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0,5,1
3,TV Show,Jailbirds New Orleans,Rajiv Chilaka,United States,2021,TV-MA,1,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0,5,1
4,TV Show,Kota Factory,Rajiv Chilaka,India,2021,TV-MA,2,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0,5,2

In [232]:
df["country"].value_counts()

country
United States                                                      3649
India                                                               972
United Kingdom                                                      419
Japan                                                               245
South Korea                                                         199
                                                                   ...
Mexico, United States, Spain, Colombia                                1
Canada, Norway                                                        1
Finland, Germany, Belgium                                             1
Argentina, United States, Mexico                                      1
United Kingdom, United States, Germany, Denmark, Belgium, Japan       1
Name: count, Length: 748, dtype: int64

In [233]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['type']=le.fit_transform(df['type'])
df['director']=le.fit_transform(df['director'])
df['country']=le.fit_transform(df['country'])
df['rating']=le.fit_transform(df['rating'])
df['listed_in']=le.fit_transform(df['listed_in'])
df['description']=le.fit_transform(df['description'])
df['title']=le.fit_transform(df['title'])

In [234]:
df.columns

Index(['type', 'title', 'director', 'country', 'release_year', 'rating',
       'duration', 'listed_in', 'description', 'year_added', 'month_added',
       'content_age', 'duration_minutes'],
      dtype='object')

In [235]:
df['rating'].unique()

array([ 7, 11,  6,  9, 12, 13, 14,  8, 10,  3,  4,  1,  2,  0,  5, 15, 16])

In [236]:
df['type'].unique()

array([0, 1])

In [237]:
df.head()

,type,title,director,country,release_year,rating,duration,listed_in,description,year_added,month_added,content_age,duration_minutes
0,0,1975,2295,603,2020,7,90,274,2577,2021.0,9.0,6,90
1,1,1091,3392,426,2021,11,2,414,1762,2021.0,9.0,5,2
2,1,2651,2105,603,2021,11,1,242,7341,2021.0,9.0,5,1
3,1,3506,3392,603,2021,11,1,297,3617,2021.0,9.0,5,1
4,1,3861,3392,251,2021,11,2,393,4416,2021.0,9.0,5,2

In [238]:
x=df.drop(['type','description','title','director','duration','duration_minutes'],axis=1)
y=df['type']

In [239]:
x.columns

Index(['country', 'release_year', 'rating', 'listed_in', 'year_added',
       'month_added', 'content_age'],
      dtype='object')

In [267]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [280]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=2)
model.fit(x_train,y_train)

RandomForestClassifier(n_estimators=2)

In [281]:
y_pred=model.predict(x_test)

In [282]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))

0.9160045402951191

In [283]:
print("test score",model.score(x_test,y_test))
print("train score",model.score(x_train,y_train))

test score 0.9160045402951191
train score 0.9635202271114266

In [284]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[1206    8]
 [ 140  408]]
              precision    recall  f1-score   support

           0       0.90      0.99      0.94      1214
           1       0.98      0.74      0.85       548

    accuracy                           0.92      1762
   macro avg       0.94      0.87      0.89      1762
weighted avg       0.92      0.92      0.91      1762

**DECISION TREE**

In [285]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(max_depth=5)
dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=5)

In [286]:
y_pred=dt.predict(x_test)

In [287]:
print(accuracy_score(y_test,y_pred))

0.8938706015891033

In [288]:
print("test score",dt.score(x_test,y_test))
print("train score",dt.score(x_train,y_train))

test score 0.8938706015891033
train score 0.9048970901348474

In [289]:
import pickle
with open("model.pkl", "wb") as f:
  pickle.dump(model, f)
from google.colab import files
files.download("model.pkl")